// Code generated by hertz generator.

package main

import (
	"douyin/cmd/api/biz/rpc"
	"douyin/cmd/api/conn"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	rpc.Init()
	conn.InitRedis()
	conn.InitWordsFilter()
	h := server.Default(server.WithHostPorts("127.0.0.1:8080"))

	register(h)
	h.Spin()
}
