// Code generated by hertz generator.

package main

import (
	handler "douyin/cmd/api/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	//r.GET("/user/", handler.UserInfo)
	r.POST("/douyin/user/register/", handler.Register)
	r.POST("/douyin/user/login/", handler.Login)
}
